/*
    다대다 관계
    1. 2개의 테이블을 직접 관계 짓는 것은 불가능하다.
    2. 다대다 관계를 가지는 2개의 테이블과 연결될 중간 테이블이 필요하다.
    3. 일대다 관계를 2개 만들면 다대다 관계가 된다.
*/

-- 학생 - 과목 - 수강신청

-- 학생 테이블
CREATE TABLE STUDENT_T(
    STUDENT_NO NUMBER NOT NULL PRIMARY KEY,
    STUDENT_NAME VARCHAR2(100 BYTE) NOT NULL,
    GRADE NUMBER NOT NULL,
    CLASS NUMBER NOT NULL,
    CLASS_NO NUMBER NOT NULL
);

-- 과목 테이블
CREATE TABLE SUBJECT_T(
    SUBJECT_CODE VARCHAR2(10 BYTE) NOT NULL PRIMARY KEY,
    SUBJECT_NAME VARCHAR2(100 BYTE) NOT NULL,
    PROFESSOR_NAME VARCHAR2(100 BYTE) NOT NULL
);

-- 수강신청 테이블
CREATE TABLE SUGANG_T(
    SUGANG_NO NUMBER NOT NULL PRIMARY KEY,
    -- 학생이 지워지면 수강신청도 지워진다.
    STUDENT_NO NUMBER REFERENCES STUDENT_T(STUDENT_NO) ON DELETE CASCADE,
    -- 과목이 지워지면 수강신청에서 과목을 NULL로 설정한다.
    SUBJECT_CODE VARCHAR2(10 BYTE) REFERENCES SUBJECT_T(SUBJECT_CODE) ON DELETE SET NULL
);

INSERT INTO STUDENT_T VALUES(10101, '가길동', 1, 1, 1);
INSERT INTO SUBJECT_T VALUES('A', '국어', '김세종');
INSERT INTO SUGANG_T VALUES(1, 10101, 'A');
DELETE FROM STUDENT_T WHERE STUDENT_NO = 10101;
DELETE FROM SUBJECT_T WHERE SUBJECT_CODE = 'A';

DROP TABLE SUGANG_T;
DROP TABLE STUDENT_T;
DROP TABLE SUBJECT_T;